dist: bionic
language: c
addons:
  apt:
    packages:
    - jq
    - doxygen
    - graphviz
    - python3.8
    - python3-pip
    - python3-setuptools
cache:
  directories:
    - "~/.platformio"
before_install:
  - python --version && pip --version
  - python3 --version && pip3 --version
script: echo Running checks
notifications:
  email:
    on_success: change
    on_failure: change
jobs:
  include:
    - name: "Doc checks"
      script:
      - (DOXYGEN_OUTPUT=$(doxygen 2>&1); if [[ $? -ne 0 || -n "${DOXYGEN_OUTPUT}" ]]; then echo "${DOXYGEN_OUTPUT}"; exit 1; fi)
