# This is a basic workflow that is triggered on push/PRs to the master branch.

name: Documentation

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SteffenSeckler/doxygen-action@v2.2.0beta4
        with:
            fail-on-warnings: true
