name: Linter

on: [push]

jobs:
  Linters:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        shopt -s nullglob
        pylint -d F0001 {src,test,tools}/*.py
    - name: Analysing the code with cpplint
      run: |
        wget https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
        shopt -s nullglob
        python cpplint.py --extensions=c,cc,cpp,ino --headers=h,hpp {src,src/locale,test,tools}/*.{h,c,cc,cpp,hpp,ino} examples/*/*.{h,c,cc,cpp,hpp,ino}
